// Seed Data: External learning platforms

export const PLATFORMS = [
    {
        id: 'ev-org',
        name: 'Escola Virtual (Fundação Bradesco)',
        logo_url: 'https://www.ev.org.br/favicon.ico',
        base_url: 'https://www.ev.org.br',
        signup_url: 'https://www.ev.org.br/cadastro',
        certificate_type: 'digital_download' as const,
        certificate_instructions: 'Ao completar o curso, baixe o certificado na seção "Meus Certificados".',
        requires_cpf: true,
        requires_phone: false,
        is_free: true,
        avg_course_hours: 20,
    },
    {
        id: 'dio',
        name: 'DIO',
        logo_url: null,
        base_url: 'https://www.dio.me',
        signup_url: 'https://www.dio.me/sign-up',
        certificate_type: 'digital_link' as const,
        certificate_instructions: 'Certificado disponível no perfil após conclusão do bootcamp.',
        requires_cpf: false,
        requires_phone: false,
        is_free: true,
        avg_course_hours: 15,
    },
    {
        id: 'youtube',
        name: 'YouTube',
        logo_url: null,
        base_url: 'https://www.youtube.com',
        signup_url: 'https://www.youtube.com',
        certificate_type: null,
        certificate_instructions: null,
        requires_cpf: false,
        requires_phone: false,
        is_free: true,
        avg_course_hours: null,
    },
    {
        id: 'cursoemvideo',
        name: 'Curso em Vídeo',
        logo_url: null,
        base_url: 'https://www.cursoemvideo.com',
        signup_url: 'https://www.cursoemvideo.com/register',
        certificate_type: 'digital_download' as const,
        certificate_instructions: 'Complete todos os exercícios e baixe o certificado.',
        requires_cpf: false,
        requires_phone: false,
        is_free: true,
        avg_course_hours: 40,
    },
];
